# Generated by Django 5.0.7 on 2024-10-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_alter_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='mode_preparo',
            new_name='modo_preparo',
        ),
    ]
